version: "3.7"

services:
  tarantool:
    image: keithzetterstrom/tabutask_tarantool
    container_name: tabutask_tarantool
    expose:
      - 3301
    volumes:
      - /home/ubuntu/data/tarantool:/var/lib/tarantool

  auth:
    image: keithzetterstrom/tabutask_auth
    container_name: tabutask_auth
    restart: always
    expose:
      - 9081
    env_file:
      - config.env
    depends_on:
      - tarantool

  postgres:
    image: postgres
    container_name: tabutask_postgres
    expose:
      - 5432
    env_file:
      - init/database.env
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/

  board:
    image: keithzetterstrom/tabutask_board
    container_name: tabutask_board
    restart: always
    expose:
      - 9083
    env_file:
      - config.env
    volumes:
      - ./attachments:/attachments
    depends_on:
      - postgres

  profile:
    image: keithzetterstrom/tabutask_profile
    container_name: tabutask_profile
    restart: always
    expose:
      - 9082
    env_file:
      - config.env
    volumes:
      - ./avatars:/avatars
      - ./default:/default
    depends_on:
      - postgres

  main:
    image: keithzetterstrom/tabutask_main
    container_name: tabutask_main
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./avatars:/avatars
      - ./default:/default
      - ./attachments:/attachments
    env_file:
      - config.env
